const prompt = require("prompt-sync")();

/* for(let a=0; a<400; a++){
    console.log(a+1)
}
 */
/* let obj = {
harry: 90,
Raju: 50,
Eama: 30
}
for (a in obj){
    console.log("Mark of a " + a + " are " + obj[a]);
} */


let me = {
    Aritro: 40,
    Raju: 30,
    Roky: 50 
}

for (let a of "Aritro"){
    console.log(a); 
}
console.log("-------------------------------");
for (let b of "Raju"){
    console.log(b);
}

/* let sum = 0;
let n = prompt("Enter the value of n? ");

for(let i=0; i<n; i++){
    sum += (i+1);
}
console.log("The value of N is " + n + " and the sum is = " + sum);
console.log(i); */